import httpx
import re
from rich.console import Console
from rich.panel import Panel
from rich.markdown import Markdown
from rich import box
from brax.core.config import Config
from brax.core.github import GitHubManager
from brax.agents.debugger import DebuggerAgent
from brax.agents.reviewer import ReviewerAgent

console = Console()


def resolve_cmd(issue_url: str):
    config = Config()
    if not config.is_onboarded():
        console.print("[yellow]⚠ Run [bold]brax onboard[/bold] first.[/yellow]")
        return

    match = re.match(r"https?://github\.com/([^/]+)/([^/]+)/issues/(\d+)", issue_url)
    if not match:
        # Try owner/repo#issue format
        match = re.match(r"([^/]+)/([^/#]+)#(\d+)", issue_url)
        if not match:
            console.print("[red]Invalid GitHub issue URL. Use: https://github.com/owner/repo/issues/123[/red]")
            return

    owner, repo, issue_num = match.group(1), match.group(2), match.group(3)

    # Validate inputs
    repo = repo.replace(".git", "")
    try:
        int(issue_num)
    except ValueError:
        console.print("[red]Invalid issue number[/red]")
        return

    console.print(Panel(
        f"[bold cyan]BRAX Resolve[/bold cyan]\n\n"
        f"[white]{owner}/{repo} #{issue_num}[/white]",
        title=" GitHub Issue Resolution ",
        box=box.ROUNDED,
        border_style="cyan",
        padding=(1, 2)
    ))

    token = config.get_github_token()
    headers = {"Authorization": f"Bearer {token}"} if token else {}

    console.print("[dim]Fetching issue details...[/dim]")
    try:
        r = httpx.get(
            f"https://api.github.com/repos/{owner}/{repo}/issues/{issue_num}",
            headers=headers,
            timeout=15
        )
        if r.status_code != 200:
            console.print(f"[red]Failed to fetch issue: {r.status_code} {r.text[:200]}[/red]")
            return
        issue = r.json()
    except Exception as e:
        console.print(f"[red]Error fetching issue: {e}[/red]")
        return

    title = issue.get("title", "No title")
    body = issue.get("body", "No description") or "No description"
    labels = ", ".join(l["name"] for l in issue.get("labels", []))

    console.print(f"\n[bold]Issue:[/bold] {title}")
    if labels:
        console.print(f"[bold]Labels:[/bold] {labels}")
    console.print(f"\n[dim]{body[:1000]}[/dim]\n")

    debugger = DebuggerAgent()

    console.print("[dim]Agent is analyzing and fixing the issue...[/dim]")
    fix = debugger.think(
        f"Fix this GitHub issue:\n\n"
        f"Repository: {owner}/{repo}\n"
        f"Issue #{issue_num}: {title}\n\n"
        f"Description:\n{body[:3000]}\n\n"
        f"Output the fix using:\nFILE: path/to/file\n```\ncode\n```\n"
        f"Explain what the issue was and how you fixed it."
    )

    console.print("\n" + "─" * console.width)
    console.print("[bold]Proposed Fix:[/bold]\n")
    console.print(Markdown(fix))
    console.print("\n" + "─" * console.width)

    # Create PR via GitHub API
    if token:
        gh = GitHubManager(token)
        user = gh.get_user()
        if user:
            console.print("[dim]Creating fork and pull request...[/dim]")
            try:
                # Fork the repo
                r = httpx.post(
                    f"https://api.github.com/repos/{owner}/{repo}/forks",
                    headers={"Authorization": f"Bearer {token}", "Accept": "application/vnd.github+json"},
                    timeout=15
                )
                if r.status_code not in (200, 202):
                    console.print(f"[yellow]Could not fork repo (may already exist)[/yellow]")

                # Create PR via API
                pr_body = f"## Fixes #{issue_num}\n\n{title}\n\n---\n\n_Generated by BRAX AI Dev Team_"
                r = httpx.post(
                    f"https://api.github.com/repos/{owner}/{repo}/pulls",
                    headers={
                        "Authorization": f"Bearer {token}",
                        "Content-Type": "application/json",
                        "Accept": "application/vnd.github+json"
                    },
                    json={
                        "title": f"Fix: {title[:72]}",
                        "body": pr_body,
                        "head": f"{user}:brax-fix-{issue_num}",
                        "base": issue.get("base", {}).get("ref", "main")
                    },
                    timeout=15
                )
                if r.status_code in (200, 201):
                    pr_url = r.json().get("html_url", "")
                    console.print(f"  [green]✓[/green] PR created: [cyan]{pr_url}[/cyan]")
                else:
                    console.print(f"[yellow]PR creation: {r.status_code} (push may need manual setup)[/yellow]")
            except Exception as e:
                console.print(f"[yellow]Could not auto-create PR: {e}[/yellow]")

    console.print("[green]✓[/green] Resolution complete")
