import os
import subprocess
import httpx
from pathlib import Path
from rich.console import Console
from rich.panel import Panel

console = Console()


def check_gh_cli() -> bool:
    try:
        subprocess.run(["gh", "--version"], capture_output=True, check=True)
        return True
    except (FileNotFoundError, subprocess.CalledProcessError):
        return False


def install_gh_cli():
    if check_gh_cli():
        return True
    console.print("  [yellow]~[/yellow] GitHub CLI not found. Attempting install...")
    import sys
    try:
        if sys.platform == "linux":
            subprocess.run(["apt-get", "install", "-y", "gh"], capture_output=True, check=False)
        elif sys.platform == "darwin":
            subprocess.run(["brew", "install", "gh"], capture_output=True, check=False)
        elif sys.platform == "win32":
            subprocess.run(["winget", "install", "GitHub.cli"], capture_output=True, check=False)
        if check_gh_cli():
            console.print("  [green]✓[/green] GitHub CLI installed")
            return True
    except Exception:
        pass
    return False


class GitHubManager:
    def __init__(self, token: str = ""):
        self.token = token or os.getenv("GITHUB_TOKEN", "")

    def is_authed(self) -> bool:
        return bool(self.token)

    def test_token(self) -> bool:
        if not self.token:
            return False
        try:
            r = httpx.get(
                "https://api.github.com/user",
                headers={"Authorization": f"Bearer {self.token}"},
                timeout=10
            )
            return r.status_code == 200
        except Exception:
            return False

    def get_user(self) -> str | None:
        try:
            r = httpx.get(
                "https://api.github.com/user",
                headers={"Authorization": f"Bearer {self.token}"},
                timeout=10
            )
            if r.status_code == 200:
                return r.json().get("login")
        except Exception:
            pass
        return None

    def repo_exists(self, name: str) -> bool:
        user = self.get_user()
        if not user:
            return False
        try:
            r = httpx.get(
                f"https://api.github.com/repos/{user}/{name}",
                headers={"Authorization": f"Bearer {self.token}"},
                timeout=10
            )
            return r.status_code == 200
        except Exception:
            return False

    def create_repo(self, name: str, private: bool = True) -> bool:
        try:
            r = httpx.post(
                "https://api.github.com/user/repos",
                headers={
                    "Authorization": f"Bearer {self.token}",
                    "Content-Type": "application/json",
                    "Accept": "application/vnd.github+json",
                },
                json={
                    "name": name,
                    "private": private,
                    "auto_init": False,
                    "description": f"Generated by BRAX AI Dev Team"
                },
                timeout=15
            )
            return r.status_code in (200, 201)
        except Exception:
            return False

    def push_repo(self, project_dir: Path, repo_name: str) -> bool:
        user = self.get_user()
        if not user:
            console.print("  [red]✗[/red] Could not determine GitHub user")
            return False

        remote_url = f"https://x-access-token:{self.token}@github.com/{user}/{repo_name}.git"

        try:
            from git import Repo
            repo = Repo(project_dir)

            if not repo.remotes:
                repo.create_remote("origin", remote_url)
            else:
                repo.remote("origin").set_url(remote_url)

            repo.git.branch("-M", "main")
            repo.remote("origin").push("main", force=True)
            console.print(f"  [green]✓[/green] Pushed to: https://github.com/{user}/{repo_name}")
            return True
        except Exception as e:
            console.print(f"  [red]✗[/red] Push failed: {e}")
            return False

    def setup_and_push(self, project_dir: Path) -> bool:
        if not self.is_authed():
            console.print("  [dim]No GitHub token configured. Skipping push.[/dim]")
            return False

        name = project_dir.name
        if self.repo_exists(name):
            console.print(f"  [yellow]~[/yellow] Repo {name} already exists, pushing...")
        else:
            console.print(f"  [dim]Creating GitHub repo: {name}[/dim]")
            if not self.create_repo(name):
                console.print("  [red]✗[/red] Failed to create repo")
                return False

        return self.push_repo(project_dir, name)
