import json
from pathlib import Path
from concurrent.futures import ThreadPoolExecutor, as_completed
from rich.console import Console
from rich.panel import Panel
from rich.progress import Progress, SpinnerColumn, TextColumn

from brax.core.file_writer import FileWriter
from brax.core.config import Config
from brax.core.provider import count_tokens, get_model_limits, truncate_text
from brax.core.github import GitHubManager
from brax.agents.pm import PMAgent
from brax.agents.architect import ArchitectAgent
from brax.agents.frontend import FrontendAgent
from brax.agents.backend import BackendAgent
from brax.agents.database import DatabaseAgent
from brax.agents.devops import DevOpsAgent
from brax.agents.reviewer import ReviewerAgent
from brax.agents.debugger import DebuggerAgent

console = Console()


class Orchestrator:
    def __init__(self, show_diff: bool = False):
        self.show_diff = show_diff
        self.pm = PMAgent()
        self.architect = ArchitectAgent()
        self.frontend = FrontendAgent()
        self.backend = BackendAgent()
        self.database = DatabaseAgent()
        self.devops = DevOpsAgent()
        self.reviewer = ReviewerAgent()
        self.debugger = DebuggerAgent()
        self.writer: FileWriter | None = None
        self.project_name = ""
        self._repo = None

    def run(self, description: str):
        config = Config()
        workspace = config.get_workspace()
        project_name = self._santize_name(description)
        self.project_name = project_name
        project_dir = workspace / project_name
        self.writer = FileWriter(project_dir, show_diff=self.show_diff)

        console.print(Panel(f"[bold cyan]BRAX Dev Team[/bold cyan]\n\n[white]{description}[/white]",
                            title=" New Project Request ", border_style="cyan"))

        self._init_git(project_dir)

        plan = self._phase_pm_analyze(description)
        self._git_commit("PM analysis complete")

        architecture = self._phase_architect_design(plan)
        self._write_braxmd(project_dir, architecture)
        self._git_commit("Architecture design complete")

        self._phase_pm_assign(architecture)

        self._phase_build_parallel(architecture)

        self._phase_review()

        self._write_readme(project_dir)
        self._git_commit("Project complete")

        self._phase_github_push(project_dir)

        self._phase_finalize(project_dir)

    def _init_git(self, project_dir: Path):
        try:
            from git import Repo
            self._repo = Repo.init(project_dir)
            with open(project_dir / ".gitignore", "w") as f:
                f.write("__pycache__/\n*.pyc\n.env\nnode_modules/\n")
            self._repo.index.add([".gitignore"])
            self._repo.index.commit("Initial commit")
        except ImportError:
            self._repo = None

    def _git_commit(self, message: str):
        if not self._repo or not self.writer:
            return
        try:
            self._repo.index.add("*")
            if self._repo.index.diff("HEAD") or self._repo.untracked_files:
                self._repo.index.commit(f"BRAX: {message}")
        except Exception:
            pass

    def _write_braxmd(self, project_dir: Path, architecture: str):
        brax_path = project_dir / "BRAX.md"
        content = f"""# BRAX Project Context

Generated by BRAX AI Dev Team.

## Project
{self.project_name}

## Architecture
{architecture[:2000]}

## Instructions
- This project was generated by autonomous AI agents.
- Agents read this file for project context on subsequent builds.
- To rebuild or extend, run: brax create "<description>"
- To chat with agents about this project: brax chat
"""
        brax_path.write_text(content)

    def _write_readme(self, project_dir: Path):
        files = []
        for f in sorted(project_dir.rglob("*")):
            if f.is_file() and f.name != ".gitignore" and ".git" not in f.parts:
                rel = f.relative_to(project_dir)
                files.append(f"  - {rel}")

        structure = "\n".join(files[:50])
        if len(files) > 50:
            structure += f"\n  - ... and {len(files) - 50} more files"

        readme = f"""# {self.project_name}

Generated by [BRAX](https://opencode.ai) — AI Dev Team.

## Project Structure

{structure}

## Quick Start

See instructions in each service directory.

## Tech Stack

Determined by the Architect agent during generation.
"""
        self.writer.write_file("README.md", readme)

    def _phase_pm_analyze(self, description: str) -> str:
        with Progress(SpinnerColumn(), TextColumn("[progress.description]{task.description}"), transient=True) as p:
            p.add_task(description="PM is analyzing your request...", total=None)
            plan = self.pm.think(
                f"Analyze this project request and create a detailed plan:\n{description}\n\n"
                f"Output tasks as JSON with assigned_to for each task."
            )
            self.pm.send("architect", "Project plan ready", "plan")
        return plan

    def _phase_architect_design(self, plan: str) -> str:
        with Progress(SpinnerColumn(), TextColumn("[progress.description]{task.description}"), transient=True) as p:
            p.add_task(description="Architect is designing the system...", total=None)
            architecture = self.architect.think(
                f"Design the system architecture based on this plan:\n{plan}\n\n"
                f"Include: tech stack, folder structure, API contracts, database schema, env variables."
            )
            self.architect.send("pm", "Architecture design complete", "design")
        return architecture

    def _phase_pm_assign(self, architecture: str):
        with Progress(SpinnerColumn(), TextColumn("[progress.description]{task.description}"), transient=True) as p:
            p.add_task(description="PM is assigning tasks to the team...", total=None)
            tasks = self.pm.think(
                f"Review this architecture and assign specific build tasks:\n{architecture}\n\n"
                f"Assign to: frontend, backend, database, devops."
            )
            for agent_name in ["frontend", "backend", "database", "devops"]:
                self.pm.send(agent_name, f"Your task based on architecture:\n{architecture}\n\nTasks:\n{tasks}", "task")

    def _phase_build_parallel(self, architecture: str):
        builders = [
            ("frontend", self.frontend),
            ("backend", self.backend),
            ("database", self.database),
            ("devops", self.devops),
        ]

        with Progress(SpinnerColumn(), TextColumn("[progress.description]{task.description}"), transient=True) as p:
            task_map = {}
            for label, agent in builders:
                task = p.add_task(description=f"{label.title()} agent is building...", total=None)
                task_map[label] = task

            with ThreadPoolExecutor(max_workers=4) as executor:
                futures = {}
                for label, agent in builders:
                    future = executor.submit(self._build_one, label, agent, architecture)
                    futures[future] = label

                for future in as_completed(futures):
                    label = futures[future]
                    try:
                        future.result()
                        console.print(f"  [green]✓[/green] {label.title()} complete")
                    except Exception as e:
                        console.print(f"  [red]✗[/red] {label.title()} failed: {e}")

    def _build_one(self, label: str, agent, architecture: str):
        inbox = agent.inbox()
        task_msgs = [m for m in inbox if m.msg_type == "task"]
        context = task_msgs[-1].content if task_msgs else architecture

        max_input = get_model_limits(agent.provider.model)["max_input"]
        context = truncate_text(context, max_input // 3)

        result = agent.think(
            f"Build the {label} based on this architecture and task:\n{context}\n\n"
            f"Output files using:\nFILE: path/to/file\n```\ncode\n```"
        )
        self._parse_and_write_files(result, label)
        agent.send("pm", f"{label.title()} build complete", "complete")
        self._git_commit(f"{label.title()} build complete")

    def _phase_review(self):
        files = self._get_project_files()
        if not files:
            return

        self.pm.send("reviewer", "All code is ready for review", "review")

        max_review_input = get_model_limits(self.reviewer.provider.model)["max_input"]
        files = truncate_text(files, max_review_input // 2)

        with Progress(SpinnerColumn(), TextColumn("[progress.description]{task.description}"), transient=True) as p:
            p.add_task(description="Reviewer is checking all code...", total=None)
            review = self.reviewer.think(f"Review all files in the project:\n{files}")

            if "issue" in review.lower() or "fix" in review.lower():
                self.reviewer.send("debugger", "Issues found that need fixing", "issues")

                max_debug_input = get_model_limits(self.debugger.provider.model)["max_input"]
                truncated_review = truncate_text(review, max_debug_input // 3)
                p.add_task(description="Debugger is fixing issues...", total=None)
                fixes = self.debugger.think(f"Fix these review issues:\n{truncated_review}")
                self._parse_and_write_files(fixes, "fixes")
                self.debugger.send("reviewer", "Fixes applied, please re-review", "fixed")
                self._git_commit("Bug fixes applied")

        console.print("  [green]✓[/green] Review complete")

    def _phase_finalize(self, project_dir: Path):
        self.pm.send("pm", "All agents have reported completion. Generating summary.", "status")
        summary = self.pm.think(
            f"The project is complete. Write a final summary of what was built:\nProject: {self.project_name}")

        lessons_raw = self.pm.think(
            f"Based on this project ({self.project_name}), what key lessons should each agent learn?\n"
            f"Output a JSON object mapping agent names to a single lesson string each."
        )
        try:
            lessons = json.loads(lessons_raw)
        except json.JSONDecodeError:
            lessons = {}

        for agent_name, lesson in lessons.items():
            agent = getattr(self, agent_name, None)
            if agent and lesson:
                agent.learn(lesson)

        for agent in [self.pm, self.architect, self.frontend, self.backend,
                      self.database, self.devops, self.reviewer, self.debugger]:
            agent.memory.record_project(agent.name, self.project_name)

        console.print(Panel(summary, title=" Project Complete ", border_style="green"))
        console.print(f"\n[bold green]✓[/bold green] Project created at: [cyan]{project_dir}[/cyan]")

    def _phase_github_push(self, project_dir: Path):
        config = Config()
        if not config.get_github_autopush():
            return
        token = config.get_github_token()
        if not token:
            return
        gh = GitHubManager(token)
        console.print("  [dim]Pushing to GitHub...[/dim]")
        gh.setup_and_push(project_dir)

    def _parse_and_write_files(self, text: str, phase: str):
        if not self.writer:
            return
        lines = text.split("\n")
        current_file = None
        current_content = []
        in_code_block = False

        for line in lines:
            if line.startswith("FILE:"):
                if current_file and current_content:
                    content = "\n".join(current_content)
                    self.writer.write_file(current_file, content)
                file_part = line.replace("FILE:", "").strip()
                current_file = file_part.split("```")[0].strip()
                current_content = []
                in_code_block = "```" in line
            elif line.strip().startswith("```"):
                if in_code_block:
                    in_code_block = False
                else:
                    in_code_block = True
            elif in_code_block:
                current_content.append(line)

        if current_file and current_content:
            content = "\n".join(current_content)
            self.writer.write_file(current_file, content)

    def _get_project_files(self) -> str:
        if not self.writer:
            return ""
        project_dir = self.writer.project_dir
        if not project_dir.exists():
            return ""
        files = []
        for f in project_dir.rglob("*"):
            if f.is_file():
                rel = f.relative_to(project_dir)
                files.append(f"{rel}\n{f.read_text()[:200]}")
        return "\n---\n".join(files)

    @staticmethod
    def _santize_name(description: str) -> str:
        words = description.lower().split()[:4]
        clean = "".join(c for c in " ".join(words) if c.isalnum() or c in " -_")
        return clean.replace(" ", "-") or "project"
